# Permalinks
#
#permalink:           pretty
permalink:           date

# Setup
title:               'Hop and Fork'
tagline:             'Work in progress...'
description:         'Open Source team @ University of Rome Tor Vergata'
#url:                 http://lanyon.getpoole.com
baseurl: '' 
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"


# Custom vars
version:             1.0.0
